### ISSUE TITLE
API for Recovered and Death data

### ISSUE THREAD

**Issue by salemcoe** [hyubs/ncovph#17]
Can we place an API for recovered and death data?
or can we simply place a column from confirmed cases with remarks of recovered or death?

**Comment by hubertursua** [comment]
It’s supposed to be the **status** field but the data from the DOH ArcGIS is missing right now for the local confirmed cases. 

I’m still looking for a primary source to fill this up or I might rely on secondary sources (e.g. community-pooled data, semi-manually inputted) and mark it as such.

**Comment by imlyrrad** [comment]
It has an API for COVID statistics in DOH ArcGIS ready, i already use it on my applications,

![app](https://user-images.githubusercontent.com/12760535/77815910-8c39fe80-70f9-11ea-820f-65e3a0a1df92.png)

**Comment by hubertursua** [comment]
@imlyrrad I'm currently working on the confirmed and PUI counts per hospital right now. What @salemcoe was referring to is the status of confirmed cases (i.e. recovered, deceased, stable), which is a totally different thing.

**Comment by hubertursua** [comment]
Dates and status for recovered and deceased cases are now available in the latest version of the API.
