### ISSUE TITLE
Status is always unspecified

### ISSUE THREAD

**Issue by rimzbravz** [hyubs/ncovph#18]
![image](https://user-images.githubusercontent.com/7781065/77850519-b24cc500-7205-11ea-925d-1ad670344047.png)

**Comment by hubertursua** [comment]
Sadly, the data from ArcGIS has the status blank.

I think I know the Google Sheet version that you are referring to. The status there is manually inputted based on the press releases. 

I'll be doing the same mid-next week after I've converted all the other endpoints. It seems DOH has no plans of updating the status field in ArcGIS anytime soon.

**Comment by hubertursua** [comment]
Dates and status for recovered and deceased cases are now available in the latest version of the API.

For local cases, status will be `UNSPECIFIED`, `RECOVERED`, or `DECEASED`.

Some sources include the status `STABLE` and `ADMITTED` but in my opinion, this is a very unreliable and often outdated. DOH no longer reports these.
