### ISSUE TITLE
confirmed-case is returning ofw-cases

### ISSUE THREAD

**Issue by ardee925** [hyubs/ncovph#23]
https://ncovph.com/api/confirmed-cases is returning the same data as
https://ncovph.com/api/ofw-cases

We are using your API for Project Greengrass btw. 

Thanks for this API! Good work!

**Comment by hubertursua** [comment]
Confirming this. I'll have the fix in a few minutes.

What's the link to Project Greengrass?

**Comment by ardee925** [comment]
greengrass.things.ph

**Comment by hubertursua** [comment]
The issue has been resolved. Thanks for reporting! Broke the local cases when I migrated to the new backend.

Awesome work on project greengrass!
