### ISSUE TITLE
Share your work here

### ISSUE THREAD

**Issue by hubertursua** [hyubs/ncovph#24]
If you're using the [ncovph API](https://ncovph.com), I'd love to know what you are building. 

I plan to make a list of projects on the website to feature your work.

And if you have any questions or problems, feel free to [open a separate issue](https://github.com/hyubs/ncovph/issues/new).

**Comment by ardee925** [comment]
https://www.facebook.com/projectgreengrass
https://greengrass.things.ph

We have added a COVID19 case heatmap layer to our street activity monitoring map. Thank you for this easy to use and well-documented API.

**Comment by alfonzm** [comment]
Hello! I use your confirmed cases API for https://bantaycovid.com.

Will probably be adding a map soon too. I hope DOH will continue providing details consistently so it won't mess up the API. 😁

Thank you for making this!

**Comment by jannomeister** [comment]
Hi @hyubs 

I made a simple website that shows some graphs related to COVID-19 situations. And a sidebar that tracks total confirmed cases per region. (this is the part where I used your API) :)

Here's the link: [PH NCOV Tracker](https://ecstatic-hypatia-d5c060.netlify.com/)
and the repo: https://github.com/jannomeister/ncov-tracker

**Comment by Pipaolo** [comment]
Helloo @hyubs,

Thank you for creating such a wonderful api, I created an android app that tracks the current status in the Philippines using your api and some data from another website. 

Here is the source code: https://github.com/Pipaolo/NCOV-Tracker-PH

**Comment by hubertursua** [comment]
Hi @Pipaolo! Thanks for the kind words. Awesome to see the new GraphQL API in action.

Be sure to check the [website](https://ncovph.com) for updates. And feel free to create an issue here on GitHub if you need any help with the API.

I'm currently working on some corrections regarding the residences data (moving from ISO 3166 to PSGC standard). After that, I'll move to the other data sets which will include PPE inventories and hospital capacities.
