### ISSUE TITLE
Confirmed cases blank

### ISSUE THREAD

**Issue by Git-newbie1** [hyubs/ncovph#33]
Nothing shows up under confirmed cases.

**Comment by hubertursua** [comment]
Confirming the issue. I’m investigating now. Should be okay within an hour.

**Comment by hubertursua** [comment]
Fixed.

Permissions glitch in the file storage server. Prevented the service from reading the last good copy of the confirmed cases.

Please note that the cases are still outdated due to the ongoing maintenance of DOH's data.
