### ISSUE TITLE
Empty Response on /api/confirmed-cases

### ISSUE THREAD

**Issue by acltabontabon** [hyubs/ncovph#6]
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/22125272/77467314-c0d25f80-6e46-11ea-9429-734cb463f1a1.png">

Was able to retrieved the response few hours ago.

Thanks and btw great work!

**Comment by hubertursua** [comment]
The service probably died and restarted. It should repopulate after a few seconds.

Let me know if it happens too often. 

I'll file a separate issue for a feature to autoload a last known copy of the data. This will ensure that you won't have those blank responses even if the service restarts.

**Comment by hubertursua** [comment]
Had an issue earlier which prevented the service from parsing the ArcGIS data (#8, #10) and continuously crashed it.
